<a href="https://colab.research.google.com/github/ValerieHazelton/Math311_Linear_Algebra_Projects/blob/main/Copy_of_Gram_Schmidt_Process_using_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ▶ Finding orthonormal vectors using the Gram Schmidt Orthonormalization Process ◀
:
Starting with the vectors:
$$ R_1 = \left (\begin{array}{c}
                3\\0\\3\\0\\
                \end{array}\right)
R_2 = \left (\begin{array}{c}
                3\\2\\3\\3\\
                \end{array}\right)
R_3 = \left (\begin{array}{c}
                -7\\-4\\-5\\-6\\
                \end{array}\right)
R_4 = \left (\begin{array}{c}
                -7\\-3\\-11\\2\\
                \end{array}\right)
$$


In [1]:
import numpy as np


In [2]:
# let's try and create a vector

v = np.array([1,2,3,4])
v2 = np.array([0,0,1,0])
v

#dot products

v.dot(v)

# we have a dot product!

# find the magnitude of a vector
# no easy code.. use v.dot(v) and take the square root

np.sqrt(v.dot(v))

# how about linear combinations
# 2*v + 3*v2

2*v + 3*v2

#yay!


array([2, 4, 9, 8])

In [3]:
#  create four vectors in numpy:
r1 = np.array([3,0,3,0])
r2 = np.array([3,2,3,3])
r3 = np.array([-7,-4,-5,-6])
r4 = np.array([-7,-3,-11,2])

r1,r2,r3,r4

(array([3, 0, 3, 0]),
 array([3, 2, 3, 3]),
 array([-7, -4, -5, -6]),
 array([ -7,  -3, -11,   2]))

In [4]:
# process the first vector
#  step 1: select r1 and subtract all the "nice" vectors

t1 = r1

#   step 2: find the magnitude of t1:

n1 = np.sqrt(t1.dot(t1))

print("the magnitude of t1=", t1, "is", n1)

# step 3: create the first "nice" vector:

u1 = (1/n1) * t1
print("u1 =", u1)

the magnitude of t1= [3 0 3 0] is 4.242640687119285
u1 = [0.70710678 0.         0.70710678 0.        ]


In [5]:
# check the reasonableness of u1:
# does u1 have size 1?

print("size of u1 is",np.sqrt(u1.dot(u1)))

# is u1 orthogonal to all other u's?

size of u1 is 1.0


In [6]:
# process the second vector
#  step 1: select r2 and subtract all the "nice" vectors

t2 = r2 - (r2.dot(u1))*u1

#   step 2: find the magnitude of t1:

n2 = np.sqrt(t2.dot(t2))

print("the magnitude of t2=", t2, "is", n2)

# step 3: create the first "nice" vector:

u2 = (1/n2) * t2
print("u2 =", u2)

the magnitude of t2= [-4.4408921e-16  2.0000000e+00 -4.4408921e-16  3.0000000e+00] is 3.605551275463989
u2 = [-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [7]:
# check the reasonableness of u2:
# does u2 have size 1?

print("size of u2 is",np.sqrt(u2.dot(u2)))

# is u1 orthogonal to all other u's?

print("dot of u1 with u2 is",u1.dot(u2))

size of u2 is 1.0
dot of u1 with u2 is -1.741861189847285e-16


In [8]:
# process the third vector
#  step 1: select r3 and subtract all the "nice" vectors

t3 = r3 - (r3.dot(u1))*u1 - (r3.dot(u2))*u2

#   step 2: find the magnitude of t2:

n3 = np.sqrt(t3.dot(t3))

print("the magnitude of t3=", t3, "is", n3)

# step 3: create the first "nice" vector:

u3 = (1/n3) * t3
print("u3 =", u3)

the magnitude of t3= [-1.0000000e+00 -4.4408921e-16  1.0000000e+00 -8.8817842e-16] is 1.4142135623730951
u3 = [-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]


In [9]:
# check the reasonableness of u3:
# does u3 have size 1?

print("size of u3 is",np.sqrt(u3.dot(u3)))

# is u3 orthogonal to all other u's?

print("dot of u3 with u2 is",u3.dot(u2))
print("dot of u3 with u1 is",u3.dot(u1))

size of u3 is 0.9999999999999999
dot of u3 with u2 is -6.967444759389139e-16
dot of u3 with u1 is 0.0


In [10]:
# process the fourth vector
#  step 1: select r4 and subtract all the "nice" vectors

t4 = r4 - (r4.dot(u1))*u1 - (r4.dot(u2))*u2 - (r4.dot(u3))*u3

#   step 2: find the magnitude of t4:

n4 = np.sqrt(t4.dot(t4))

print("the magnitude of t4=", t4, "is", n4)

# step 3: create the first "nice" vector:

u4 = (1/n4) * t4
print("u4 =", u4)

the magnitude of t4= [ 0. -3.  0.  2.] is 3.605551275463989
u4 = [ 0.         -0.83205029  0.          0.5547002 ]


In [11]:
# check the reasonableness of u4:
# does u4 have size 1?

print("size of u4 is",np.sqrt(u4.dot(u4)))

# is u4 orthogonal to all other u's?

print("dot of u4 with u3 is",u4.dot(u3))
print("dot of u4 with u2 is",u4.dot(u2))
print("dot of u4 with u1 is",u4.dot(u1))

size of u4 is 1.0
dot of u4 with u3 is -8.709305949236341e-17
dot of u4 with u2 is -1.2212453270876722e-15
dot of u4 with u1 is 0.0
